version: "3"

services:
  app:
    container_name: bshp_mpa
    image: dark_h14/bshp_v3:prod
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - TEST_MODE=true
      - DB_URL=mongodb://db:27017
      - DATASET_BATCH_LENGTH=200000
      - QUANTIZE=true        
    build:
        context: .
        dockerfile: bshp_ml/Dockerfile.prod  
    ports:
      - "8061:8061"
    volumes:
      - ./models:/models
    networks:
      - custom
    depends_on:
      - db
    restart: unless-stopped      
  db:
    image: mongo:6.0.21
    container_name: bshp_mongodb
    ports:
      - "27117:27017"
    volumes:
      - ./db/data:/data/db
    networks:
      - custom

networks:
  custom:
    driver: bridge
